# The URL the site will be built for
base_url = "https://blog.startifact.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tabi"

title = "Secret Weblog"
description = "Martijn Faassen's secret weblog"
author = "Martijn Faassen"

taxonomies = [{ name = "tags", feed = true }]

generate_feed = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# have to use the css theme with tabi theme
# https://github.com/welpo/tabi/issues/320
highlight_theme = "gruvbox-light"


[link_checker]
internal_level = "error"

[extra]
skin = "teal"


# Put all your custom variables here
menu = [
    { name = "blog", url = "posts", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]

email = "faassen@startifact.com"
encode_plaintext_email = true
feed_icon = true

socials = [
    { name = "github", url = "https://github.com/faassen/", icon = "github" },
]

footer_menu = [
    { url = "sitemap.xml", name = "Sitemap", trailing_slash = false },
]

theme_switcher = true
compact_tags = false
show_previous_next_article_links = true
toc = false
long_date_format = "%Y-%m-%d"
short_date_format = "%Y-%m-%d"
show_reading_time = false
favicon_emoji = "🫥"
copyright = "$TITLE © $CURRENT_YEAR $AUTHOR $SEPARATOR Unless otherwise noted, the content in this website is available under the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license."

allowed_domains = [
    { directive = "font-src", domains = [
        "'self'",
        "data:",
    ] },
    { directive = "img-src", domains = [
        "'self'",
        "https://*",
        "data:",
    ] },
    { directive = "media-src", domains = [
        "'self'",
    ] },
    { directive = "script-src", domains = [
        "'self'",
    ] },
    { directive = "style-src", domains = [
        "'self'",
        # inline styles won't work otherwise https://github.com/welpo/tabi/issues/320
        "'unsafe-inline'",
    ] },
    { directive = "frame-src", domains = [
        "player.vimeo.com",
        "https://www.youtube-nocookie.com",
    ] },
]
enable_csp = true

invert_previous_next_article_links = true
