# The URL the site will be built for
base_url = "https://blog.startifact.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tabi"

title = "Secret Weblog"
author = "Martijn Faassen"


taxonomies = [{ name = "tags", feed = true }]

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
menu = [
    { name = "blog", url = "posts", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]

email = "faassen@startifact.com"
encode_plaintext_email = true
feed_icon = true

footer_menu = [
    { url = "sitemap.xml", name = "Sitemap", trailing_slash = false },
]

compact_tags = false
